### ISSUE TITLE
Import bookmarks - File filter is *.htm and not *.html

### ISSUE THREAD

**Issue by francwalter** [emmyemi/bookmark-notes#15]
When I import a bookmarks file, which I exported from Firefox Bookmarks management, I get a default named file: bookmarks.html.
But when I import that now to bookmark-notes this searches as default filter only for htm-files, so the bookmarks.html is not shown. 
This is not a big deal, I can set the filter to all files (*.*) but it is not so pretty.
So please change the file filter to *.html;*.htm so the default file is shown.
Thanks.

EDIT: by the way, bookmarks-notes does NOT import my bookmarks.html file, the 'Import' Button is not activated, even not after a while.

**Comment by emmyemi** [comment]
That is odd, because the file input is actually set to accept "text/html" [(link)](https://github.com/emmyemi/bookmark-notes/blob/master/addon/pages/options.html#L27), so it should take both `.htm` and `.html` files. When I test on my system, I can successfully see to select the file even if I rename it to `.htm`, and the Import button highlights when it should.

What OS and version of Firefox are you using?

**Comment by francwalter** [comment]
Firefox 61, Windows 8.1 (64)

**Comment by ecc29** [comment]
Same issue. It doesn't work with firefox v62.02 on windows 10. The import button was always gray after file selection.

**Comment by emmyemi** [comment]
This should be fixed in 3f16676ac62e230800dbc06016fd34b60a7b7e81 in v1.1.3, just pushed to AMO.
