### ISSUE TITLE
Question: how is sync performed?

### ISSUE THREAD

**Issue by Migliutin** [emmyemi/bookmark-notes#21]
I'm quite worried about the following aspects:

- In about a year Mozilla guys intend to drop the `description` field altogether, included syncing, so exploiting **Firefox Sync** would be unreliable.
- On the other hand, would a **third party** tool guarantee data protection from breaches? 

Would you mind sharing your thoughts about it, and explaining how sync is currently performed by **Bookmark Notes** webextension?

**Comment by emmyemi** [comment]
Sure!

Firefox extensions are allowed two separate kinds of storage within the storage API: [local storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) and [synced storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync).

While much of the data for Bookmark Notes is local (options, collapsed folders, imported favicons), the notes themselves are stored using the `storage.sync` portion of the API. Anything in this section of storage is synced along with all other Firefox Sync data, and since it's part of the extension's own area of storage, it won't be affected by the removal of the description field.

**Comment by Migliutin** [comment]
Thank you very much for the quick reply! :)

One more question: is it necessary to have something besides _Bookmarks_ checked, in order for the addon to work?

![image](https://user-images.githubusercontent.com/37743077/46127174-27fe5c00-c230-11e8-944c-e54e5e3f751c.png)

**Comment by emmyemi** [comment]
You check the "Add-ons" option as well to enable Bookmark Notes to sync.
